### ISSUE TITLE
"what size is the square" throws exception

### ISSUE THREAD

**Issue by Rebecca-Qian** [facebookresearch/droidlet#158]
## Type of Issue

Select the type of issue:
- [x] Bug report (to report a bug)
- [ ] Feature request (to request an additional feature)
- [ ] Tracker (I am just using this as a tracker)
- [ ] Refactor request
- [ ] Documentation Ask

## Description

As in title

## Current Behavior

```
2021-02-17 00:17:29,945 [nsp_dialogue_manager.py:185 - handle_logical_form() INFO]: this model out: {'dialogue_type': 'GET_MEMORY', 'filters': {'output': {'attribute': 'SIZE'}, 'triples': [{'pred_text': 'has_name', 'obj_text': 'square'}]}}
2021-02-17 00:17:29,962 [loco_mc_agent.py:193 - handle_exception() ERROR]: Default handler caught exception, db_log_idx=248891
Traceback (most recent call last):
  File "/private/home/rebeccaqian/droidlet/base_agent/core.py", line 18, in start
    self.step()
  File "/private/home/rebeccaqian/droidlet/base_agent/loco_mc_agent.py", line 217, in step
    super().step()
  File "/private/home/rebeccaqian/droidlet/base_agent/core.py", line 26, in step
    self.controller_step()
  File "/private/home/rebeccaqian/droidlet/base_agent/loco_mc_agent.py", line 275, in controller_step
    self.dialogue_manager.step(incoming_chats[0])
  File "/private/home/rebeccaqian/droidlet/base_agent/dialogue_manager.py", line 99, in step
    self.dialogue_stack.step()
  File "/private/home/rebeccaqian/droidlet/base_agent/dialogue_stack.py", line 54, in step
    output_chat, step_data = self.stack[-1].step()
  File "/private/home/rebeccaqian/droidlet/base_agent/dialogue_objects/get_memory_handler.py", line 50, in step
    return self.handle_reference_object()
  File "/private/home/rebeccaqian/droidlet/base_agent/dialogue_objects/get_memory_handler.py", line 73, in handle_reference_object
    mems, vals = F()
  File "/private/home/rebeccaqian/droidlet/base_agent/memory_filters.py", line 328, in __call__
    return self.filter(mems, vals)
  File "/private/home/rebeccaqian/droidlet/base_agent/memory_filters.py", line 390, in filter
    return memids, self.attribute([self.memory.get_mem_by_id(m) for m in memids])
TypeError: 'NoneType' object is not callable
```

## Steps to reproduce

Ask bot to build a square, then ask what size is the square.

This was discovered during Droidlet oncall testing.

**Comment by snyxan** [comment]
@aszlam Is 'size' even supported? Seems not here:
https://github.com/facebookresearch/droidlet/blob/main/base_agent/dialogue_objects/attribute_helper.py#L155

**Comment by aszlam** [comment]
closed in https://github.com/facebookresearch/droidlet/pull/255
