### ISSUE TITLE
interpret_shape_schematic throws KeyError: 'cube' in schematic_helper.py

### ISSUE THREAD

**Issue by Rebecca-Qian** [facebookresearch/droidlet#302]
## Type of Issue
This is an issue discovered in agent logs from [Turk interactions](https://s3.console.aws.amazon.com/s3/object/craftassist?prefix=turk_interactions_with_agent/turk/0/).

Select the type of issue:
- [x] Bug report (to report a bug)
- [ ] Feature request (to request an additional feature)
- [ ] Tracker (I am just using this as a tracker)
- [ ] Refactor request
- [ ] Documentation Ask

## Description

```
2021-04-09 00:58:12,269 [nsp_dialogue_manager.py:333 - get_logical_form() INFO]: Querying the semantic parsing model
2021-04-09 00:58:13,126 [loco_mc_agent.py:269 - controller_step() INFO]: Incoming chats: ['<dashboard> build']
2021-04-09 00:58:14,138 [nsp_dialogue_manager.py:333 - get_logical_form() INFO]: Querying the semantic parsing model
2021-04-09 00:58:21,335 [nsp_dialogue_manager.py:172 - handle_logical_form() INFO]: logical form post-coref "45437ca8c05bcc9176b625cc8009f52c7cd36ef4ab10f638102b2d28de077267:e511cd78cefa45e5945275d42803cbaf" -> {'dialogue_type': 'HUMAN_GIVE_COMMAND', 'action_sequence': [{'action_type': 'BUILD'}]}
2021-04-09 00:58:21,336 [loco_mc_agent.py:202 - handle_exception() ERROR]: Default handler caught exception, db_log_idx=1806797
Traceback (most recent call last):
  File "/droidlet/craftassist/agent/../../base_agent/core.py", line 18, in start
    self.step()
  File "/droidlet/craftassist/agent/../../base_agent/loco_mc_agent.py", line 226, in step
    super().step()
  File "/droidlet/craftassist/agent/../../base_agent/core.py", line 26, in step
    self.controller_step()
  File "/droidlet/craftassist/agent/../../base_agent/loco_mc_agent.py", line 292, in controller_step
    self.dialogue_manager.step(incoming_chats[0])
  File "/droidlet/craftassist/agent/../../base_agent/dialogue_manager.py", line 100, in step
    self.dialogue_stack.step()
  File "/droidlet/craftassist/agent/../../base_agent/dialogue_stack.py", line 54, in step
    output_chat, step_data = self.stack[-1].step()
  File "/droidlet/craftassist/agent/../../base_agent/dialogue_objects/interpreter.py", line 103, in step
    r = self.action_handlers[action_type](self.speaker, action_def)
  File "/droidlet/craftassist/agent/../../craftassist/agent/dialogue_objects/mc_interpreter.py", line 220, in handle_build
    self, speaker, d.get("schematic", {}), repeat_dict=repeat_dict
  File "/droidlet/craftassist/agent/../../craftassist/agent/dialogue_objects/schematic_helper.py", line 230, in interpret_schematic
    blocks, tags = interpret_shape_schematic(interpreter, speaker, d)
  File "/droidlet/craftassist/agent/../../craftassist/agent/dialogue_objects/schematic_helper.py", line 137, in interpret_shape_schematic
    return SPECIAL_SHAPE_FNS[shape](**attrs), tags
KeyError: 'cube'
```

## Steps to reproduce

Commands the Turker used:
"build"

**Comment by kavyasrinet** [comment]
The issue is here: https://github.com/facebookresearch/droidlet/blob/main/craftassist/agent/dialogue_objects/mc_interpreter.py#L225

We aren't handling empty builds right now . I have brought this up with @aszlam before.

**Comment by kavyasrinet** [comment]
Pushed out a fix.
