### ISSUE TITLE
[Turk][Bug Report] "Build a small house here" raised exception

### ISSUE THREAD

**Issue by Rebecca-Qian** [facebookresearch/droidlet#327]
## Type of Issue

Select the type of issue:
- [x] Bug report (to report a bug)
- [ ] Feature request (to request an additional feature)
- [ ] Tracker (I am just using this as a tracker)
- [ ] Refactor request
- [ ] Documentation Ask

## Description

```
2021-04-02 13:50:10,726 [nsp_dialogue_manager.py:332 - get_logical_form() INFO]: Querying the semantic parsing model
INFO:root:Incoming chats: ['<dashboard> build a small house here']
2021-04-02 13:50:10,754 [loco_mc_agent.py:264 - controller_step() INFO]: Incoming chats: ['<dashboard> build a small house here']
INFO:root:Querying the semantic parsing model
2021-04-02 13:50:11,672 [nsp_dialogue_manager.py:332 - get_logical_form() INFO]: Querying the semantic parsing model
INFO:root:logical form post-coref "e60c5907188d8879b0a85ce9c553d7cda5add5562ba69f1152322e7765edeba5:4b578741c2894811b20e7f18e0c2043a" -> {'dialogue_type': 'HUMAN_GIVE_COMMAND', 'action_sequence': [{'action_type': 'BUILD', 'location': {'contains_coreference': 'resolved', 'text_span': 'here', 'reference_object': {'special_reference': 'SPEAKER'}}, 'schematic': {'filters': {'triples': [{'pred_text': 'has_name', 'obj_text': 'house'}, {'pred_text': 'has_size', 'obj_text': 'small'}]}, 'text_span': 'small house'}}]}
2021-04-02 13:50:30,506 [nsp_dialogue_manager.py:171 - handle_logical_form() INFO]: logical form post-coref "e60c5907188d8879b0a85ce9c553d7cda5add5562ba69f1152322e7765edeba5:4b578741c2894811b20e7f18e0c2043a" -> {'dialogue_type': 'HUMAN_GIVE_COMMAND', 'action_sequence': [{'action_type': 'BUILD', 'location': {'contains_coreference': 'resolved', 'text_span': 'here', 'reference_object': {'special_reference': 'SPEAKER'}}, 'schematic': {'filters': {'triples': [{'pred_text': 'has_name', 'obj_text': 'house'}, {'pred_text': 'has_size', 'obj_text': 'small'}]}, 'text_span': 'small house'}}]}
INFO:root:update_recent_entities [<base_agent.memory_nodes.PlayerNode object at 0x7ff074ca1a90>]
2021-04-02 13:50:30,509 [sql_memory.py:208 - update_recent_entities() INFO]: update_recent_entities [<base_agent.memory_nodes.PlayerNode object at 0x7ff074ca1a90>]
INFO:root:Adding 1 Build tasks to stack
2021-04-02 13:50:30,644 [mc_interpreter.py:258 - handle_build() INFO]: Adding 1 Build tasks to stack
ERROR:root:failed to place block [175   4] @ [ 2 64  7], but place_block returned True.                                 Got [0 0] instead.
2021-04-02 13:51:01,483 [tasks.py:475 - step() ERROR]: failed to place block [175   4] @ [ 2 64  7], but place_block returned True.                                 Got [0 0] instead.
ERROR:root:failed to place block [175   4] @ [ 4 64  7], but place_block returned True.                                 Got [0 0] instead.
2021-04-02 13:51:01,634 [tasks.py:475 - step() ERROR]: failed to place block [175   4] @ [ 4 64  7], but place_block returned True.                                 Got [0 0] instead.
ERROR:root:failed to place block [175   4] @ [ 1 64  7], but place_block returned True.                                 Got [0 0] instead.
2021-04-02 13:51:02,443 [tasks.py:475 - step() ERROR]: failed to place block [175   4] @ [ 1 64  7], but place_block returned True.                                 Got [0 0] instead.
ERROR:root:failed to place block [175   4] @ [ 1 64  6], but place_block returned True.                                 Got [0 0] instead.

...

2021-04-02 13:55:40,169 [craftassist_agent.py:267 - send_chat() INFO]: Sending chat: I finished building this
ERROR:root:Default handler caught exception, db_log_idx=148802
Traceback (most recent call last):
  File "/droidlet/craftassist/agent/../../base_agent/core.py", line 18, in start
    self.step()
  File "/droidlet/craftassist/agent/../../base_agent/loco_mc_agent.py", line 221, in step
    super().step()
  File "/droidlet/craftassist/agent/../../base_agent/core.py", line 23, in step
    self.perceive()
  File "/droidlet/craftassist/agent/craftassist_agent.py", line 196, in perceive
    v.perceive(force=force)
  File "/droidlet/craftassist/agent/heuristic_perception.py", line 573, in perceive
    type_name = BLOCK_DATA["bid_to_name"][idm]
KeyError: (50, 1)
2021-04-02 13:55:44,600 [loco_mc_agent.py:197 - handle_exception() ERROR]: Default handler caught exception, db_log_idx=148802
Traceback (most recent call last):
  File "/droidlet/craftassist/agent/../../base_agent/core.py", line 18, in start
    self.step()
  File "/droidlet/craftassist/agent/../../base_agent/loco_mc_agent.py", line 221, in step
    super().step()
  File "/droidlet/craftassist/agent/../../base_agent/core.py", line 23, in step
    self.perceive()
  File "/droidlet/craftassist/agent/craftassist_agent.py", line 196, in perceive
    v.perceive(force=force)
  File "/droidlet/craftassist/agent/heuristic_perception.py", line 573, in perceive
    type_name = BLOCK_DATA["bid_to_name"][idm]
KeyError: (50, 1)
```
## Current Behavior

Not being able to place a block because something is in the way - is this supposed to happen? I thought the bot would destroy whatever's in the way

**Comment by aszlam** [comment]
the error is that block (50, 1) was perceived, but it is not an actual block, at least in our lists of ids.    (50, 0) is a torch.   The previous error (which was caught) occurs when the agent tries to place a block, the placement appears to be successful, but the block in the placed location doesn't match what the agent placed.  I am going to ignore this, and then put a try catch in the heuristic perception to ignore blocks that are not in our list of ids
