### ISSUE TITLE
Too many packets in payload error

### ISSUE THREAD

**Issue by hollisma** [facebookresearch/droidlet#459]
## Type of Issue

Select the type of issue:
- [x] Bug report (to report a bug)
- [ ] Feature request (to request an additional feature)
- [ ] Tracker (I am just using this as a tracker)
- [ ] Refactor request
- [ ] Documentation Ask

## Description

An error where there are "too many packets in payload" occurs occasionally when locobot_agent.py is run. It seems to resolve itself after waiting a while (~1 min) or after restarting. 

## Steps to reproduce

The error occurs somewhat randomly whenever locobot_agent.py is run. The stack trace is as follows: 

> INFO:root:LOG LEVEL: 20
2021-06-03 06:34:28,409 [locobot_agent.py:214 - <module>() INFO]: LOG LEVEL: 20
Rootdir /raid/hollisma/droidlet
post request handler error
Traceback (most recent call last):
  File "/private/home/hollisma/.conda/envs/droidlet_env/lib/python3.7/site-packages/engineio/server.py", line 412, in handle_request
    socket.handle_post_request(environ)
  File "/private/home/hollisma/.conda/envs/droidlet_env/lib/python3.7/site-packages/engineio/socket.py", line 124, in handle_post_request
    p = payload.Payload(encoded_payload=body)
  File "/private/home/hollisma/.conda/envs/droidlet_env/lib/python3.7/site-packages/engineio/payload.py", line 13, in init
    self.decode(encoded_payload)
  File "/private/home/hollisma/.conda/envs/droidlet_env/lib/python3.7/site-packages/engineio/payload.py", line 44, in decode
    raise ValueError('Too many packets in payload')
ValueError: Too many packets in payload

**Comment by soumith** [comment]
can confirm, I'm starting to see this as well.

**Comment by snyxan** [comment]
https://github.com/miguelgrinberg/python-engineio/issues/142

**Comment by soumith** [comment]
fixed via https://github.com/facebookresearch/droidlet/pull/484
