### ISSUE TITLE
error on come here

### ISSUE THREAD

**Issue by kavyasrinet** [facebookresearch/droidlet#582]
## Type of Issue

Select the type of issue:
- [ ] Bug report (to report a bug)
- [ ] Feature request (to request an additional feature)
- [ ] Tracker (I am just using this as a tracker)
- [ ] Refactor request
- [ ] Documentation Ask

## Description

```
DEBUG:root:First top-level step()
2021-07-15 21:02:37,113 [loco_mc_agent.py:245 - step() DEBUG]: First top-level step()
INFO:root:Incoming chats: ['<ScoobyDooby12> come here']
2021-07-15 21:02:37,113 [loco_mc_agent.py:288 - perceive() INFO]: Incoming chats: ['<ScoobyDooby12> come here']
DEBUG:root:Incoming chat: ['7ce86852abbc6d90c3db31bd87233e02aa367141aeae329701a12f0cc7766985:7ba6c7a39cc143b98f6a242be4ba90ce' -> come here]
2021-07-15 21:02:37,113 [loco_mc_agent.py:298 - perceive() DEBUG]: Incoming chat: ['7ce86852abbc6d90c3db31bd87233e02aa367141aeae329701a12f0cc7766985:7ba6c7a39cc143b98f6a242be4ba90ce' -> come here]
INFO:root:Found ground truth action for "come here"
2021-07-15 21:02:37,114 [nsp_querier.py:150 - get_logical_form() INFO]: Found ground truth action for "come here"
ERROR:root:Default handler caught exception, db_log_idx=41574
Traceback (most recent call last):
  File "/private/home/kavyasrinet/droidlet/agents/core.py", line 21, in start
    self.step()
  File "/private/home/kavyasrinet/droidlet/agents/loco_mc_agent.py", line 246, in step
    super().step()
  File "/private/home/kavyasrinet/droidlet/agents/core.py", line 26, in step
    self.perceive()
  File "craftassist/craftassist_agent.py", line 234, in perceive
    super().perceive()
  File "/private/home/kavyasrinet/droidlet/agents/loco_mc_agent.py", line 312, in perceive
    chat_memid = self.memory.add_chat(self.memory.get_player_by_name(speaker).memid, preprocessed_chat)
AttributeError: 'NoneType' object has no attribute 'memid'
2021-07-15 21:02:37,124 [loco_mc_agent.py:223 - handle_exception() ERROR]: Default handler caught exception, db_log_idx=41574
Traceback (most recent call last):
  File "/private/home/kavyasrinet/droidlet/agents/core.py", line 21, in start
    self.step()
  File "/private/home/kavyasrinet/droidlet/agents/loco_mc_agent.py", line 246, in step
    super().step()
  File "/private/home/kavyasrinet/droidlet/agents/core.py", line 26, in step
    self.perceive()
  File "craftassist/craftassist_agent.py", line 234, in perceive
    super().perceive()
  File "/private/home/kavyasrinet/droidlet/agents/loco_mc_agent.py", line 312, in perceive
    chat_memid = self.memory.add_chat(self.memory.get_player_by_name(speaker).memid, preprocessed_chat)
AttributeError: 'NoneType' object has no attribute 'memid'
Traceback (most recent call last):
  File "craftassist/craftassist_agent.py", line 473, in <module>
    sa.start()
  File "/private/home/kavyasrinet/droidlet/agents/core.py", line 23, in start
    self.handle_exception(e)
  File "/private/home/kavyasrinet/droidlet/agents/loco_mc_agent.py", line 241, in handle_exception
    raise e
  File "/private/home/kavyasrinet/droidlet/agents/core.py", line 21, in start
    self.step()
  File "/private/home/kavyasrinet/droidlet/agents/loco_mc_agent.py", line 246, in step
    super().step()
  File "/private/home/kavyasrinet/droidlet/agents/core.py", line 26, in step
    self.perceive()
  File "craftassist/craftassist_agent.py", line 234, in perceive
    super().perceive()
  File "/private/home/kavyasrinet/droidlet/agents/loco_mc_agent.py", line 312, in perceive
    chat_memid = self.memory.add_chat(self.memory.get_player_by_name(speaker).memid, preprocessed_chat)
AttributeError: 'NoneType' object has no attribute 'memid'
```

**Comment by kavyasrinet** [comment]
Realized that this consistently happens when the message is issued before the parsing model finishes init.
