### ISSUE TITLE
better exception handling

### ISSUE THREAD

**Issue by kavyasrinet** [facebookresearch/droidlet#584]
## Type of Issue

Select the type of issue:
- [ ] Bug report (to report a bug)
- [ ] Feature request (to request an additional feature)
- [ ] Tracker (I am just using this as a tracker)
- [ ] Refactor request
- [ ] Documentation Ask

## Description

```
2021-07-15 21:14:42,983 [loco_mc_agent.py:288 - perceive() INFO]: Incoming chats: ['<ScoobyDooby12> come heer']
INFO:root:Querying the semantic parsing model
2021-07-15 21:14:42,984 [nsp_model_wrapper.py:65 - query_for_logical_form() INFO]: Querying the semantic parsing model
ERROR:root:Default handler caught exception, db_log_idx=73530
Traceback (most recent call last):
  File "/private/home/kavyasrinet/droidlet/agents/core.py", line 21, in start
    self.step()
  File "/private/home/kavyasrinet/droidlet/agents/loco_mc_agent.py", line 246, in step
    super().step()
  File "/private/home/kavyasrinet/droidlet/agents/core.py", line 29, in step
    self.controller_step()
  File "/private/home/kavyasrinet/droidlet/agents/loco_mc_agent.py", line 346, in controller_step
    self.memory.dialogue_stack.step(self)
  File "/private/home/kavyasrinet/droidlet/droidlet/memory/dialogue_stack.py", line 46, in step
    output_chat, step_data = self.stack[-1].step(agent=agent)
  File "/private/home/kavyasrinet/droidlet/droidlet/interpreter/interpreter.py", line 102, in step
    r = self.action_handlers[action_type](agent, self.speaker, action_def)
  File "/private/home/kavyasrinet/droidlet/droidlet/interpreter/interpreter.py", line 200, in handle_move
    return new_tasks(), None, None
  File "/private/home/kavyasrinet/droidlet/droidlet/interpreter/interpreter.py", line 172, in new_tasks
    mems = self.subinterpret["reference_locations"](self, speaker, location_d)
  File "/private/home/kavyasrinet/droidlet/droidlet/interpreter/location_helpers.py", line 65, in __call__
    interpreter, speaker, ref_obj, loose_speakerlook=loose_speakerlook
  File "/private/home/kavyasrinet/droidlet/droidlet/interpreter/reference_object_helpers.py", line 94, in __call__
    return self.interpret_reference_object(*args, **kwargs)
  File "/private/home/kavyasrinet/droidlet/droidlet/interpreter/reference_object_helpers.py", line 125, in interpret_reference_object
    mem = get_special_reference_object(interpreter, speaker, special)
  File "/private/home/kavyasrinet/droidlet/droidlet/interpreter/reference_object_helpers.py", line 68, in get_special_reference_object
    q = special_reference_search_data(None, speaker, S, entity_id=eid, agent_memory=agent_memory)
  File "/private/home/kavyasrinet/droidlet/droidlet/interpreter/reference_object_helpers.py", line 51, in special_reference_search_data
    raise Exception("unknown special reference: {}".format(S))
Exception: unknown special reference: 180
2021-07-15 21:14:44,866 [loco_mc_agent.py:223 - handle_exception() ERROR]: Default handler caught exception, db_log_idx=73530
Traceback (most recent call last):
  File "/private/home/kavyasrinet/droidlet/agents/core.py", line 21, in start
    self.step()
  File "/private/home/kavyasrinet/droidlet/agents/loco_mc_agent.py", line 246, in step
    super().step()
  File "/private/home/kavyasrinet/droidlet/agents/core.py", line 29, in step
    self.controller_step()
  File "/private/home/kavyasrinet/droidlet/agents/loco_mc_agent.py", line 346, in controller_step
    self.memory.dialogue_stack.step(self)
  File "/private/home/kavyasrinet/droidlet/droidlet/memory/dialogue_stack.py", line 46, in step
    output_chat, step_data = self.stack[-1].step(agent=agent)
  File "/private/home/kavyasrinet/droidlet/droidlet/interpreter/interpreter.py", line 102, in step
    r = self.action_handlers[action_type](agent, self.speaker, action_def)
  File "/private/home/kavyasrinet/droidlet/droidlet/interpreter/interpreter.py", line 200, in handle_move
    return new_tasks(), None, None
  File "/private/home/kavyasrinet/droidlet/droidlet/interpreter/interpreter.py", line 172, in new_tasks
    mems = self.subinterpret["reference_locations"](self, speaker, location_d)
  File "/private/home/kavyasrinet/droidlet/droidlet/interpreter/location_helpers.py", line 65, in __call__
    interpreter, speaker, ref_obj, loose_speakerlook=loose_speakerlook
  File "/private/home/kavyasrinet/droidlet/droidlet/interpreter/reference_object_helpers.py", line 94, in __call__
    return self.interpret_reference_object(*args, **kwargs)
  File "/private/home/kavyasrinet/droidlet/droidlet/interpreter/reference_object_helpers.py", line 125, in interpret_reference_object
    mem = get_special_reference_object(interpreter, speaker, special)
  File "/private/home/kavyasrinet/droidlet/droidlet/interpreter/reference_object_helpers.py", line 68, in get_special_reference_object
    q = special_reference_search_data(None, speaker, S, entity_id=eid, agent_memory=agent_memory)
  File "/private/home/kavyasrinet/droidlet/droidlet/interpreter/reference_object_helpers.py", line 51, in special_reference_search_data
    raise Exception("unknown special reference: {}".format(S))
Exception: unknown special reference: 180
Traceback (most recent call last):
  File "craftassist/craftassist_agent.py", line 473, in <module>
    sa.start()
  File "/private/home/kavyasrinet/droidlet/agents/core.py", line 23, in start
    self.handle_exception(e)
  File "/private/home/kavyasrinet/droidlet/agents/loco_mc_agent.py", line 241, in handle_exception
    raise e
  File "/private/home/kavyasrinet/droidlet/agents/core.py", line 21, in start
    self.step()
  File "/private/home/kavyasrinet/droidlet/agents/loco_mc_agent.py", line 246, in step
    super().step()
  File "/private/home/kavyasrinet/droidlet/agents/core.py", line 29, in step
    self.controller_step()
  File "/private/home/kavyasrinet/droidlet/agents/loco_mc_agent.py", line 346, in controller_step
    self.memory.dialogue_stack.step(self)
  File "/private/home/kavyasrinet/droidlet/droidlet/memory/dialogue_stack.py", line 46, in step
    output_chat, step_data = self.stack[-1].step(agent=agent)
  File "/private/home/kavyasrinet/droidlet/droidlet/interpreter/interpreter.py", line 102, in step
    r = self.action_handlers[action_type](agent, self.speaker, action_def)
  File "/private/home/kavyasrinet/droidlet/droidlet/interpreter/interpreter.py", line 200, in handle_move
    return new_tasks(), None, None
  File "/private/home/kavyasrinet/droidlet/droidlet/interpreter/interpreter.py", line 172, in new_tasks
    mems = self.subinterpret["reference_locations"](self, speaker, location_d)
  File "/private/home/kavyasrinet/droidlet/droidlet/interpreter/location_helpers.py", line 65, in __call__
    interpreter, speaker, ref_obj, loose_speakerlook=loose_speakerlook
  File "/private/home/kavyasrinet/droidlet/droidlet/interpreter/reference_object_helpers.py", line 94, in __call__
    return self.interpret_reference_object(*args, **kwargs)
  File "/private/home/kavyasrinet/droidlet/droidlet/interpreter/reference_object_helpers.py", line 125, in interpret_reference_object
    mem = get_special_reference_object(interpreter, speaker, special)
  File "/private/home/kavyasrinet/droidlet/droidlet/interpreter/reference_object_helpers.py", line 68, in get_special_reference_object
    q = special_reference_search_data(None, speaker, S, entity_id=eid, agent_memory=agent_memory)
  File "/private/home/kavyasrinet/droidlet/droidlet/interpreter/reference_object_helpers.py", line 51, in special_reference_search_data
    raise Exception("unknown special reference: {}".format(S))
Exception: unknown special reference: 180
(droidlet_env) kavyasrinet@devfair0173:~/droidlet/agents$
```

**Comment by kavyasrinet** [comment]
Looking it over again, this looks fine
