### ISSUE TITLE
"get the stone" crashes 

### ISSUE THREAD

**Issue by kavyasrinet** [facebookresearch/droidlet#586]
## Type of Issue

Select the type of issue:
- [ ] Bug report (to report a bug)
- [ ] Feature request (to request an additional feature)
- [ ] Tracker (I am just using this as a tracker)
- [ ] Refactor request
- [ ] Documentation Ask

## Description

```
2021-07-15 21:25:53,521 [loco_mc_agent.py:288 - perceive() INFO]: Incoming chats: ['<ScoobyDooby12> get the stone']
INFO:root:Querying the semantic parsing model
2021-07-15 21:25:53,522 [nsp_model_wrapper.py:65 - query_for_logical_form() INFO]: Querying the semantic parsing model
ERROR:root:Default handler caught exception, db_log_idx=221211
Traceback (most recent call last):
  File "/private/home/kavyasrinet/droidlet/agents/core.py", line 21, in start
    self.step()
  File "/private/home/kavyasrinet/droidlet/agents/loco_mc_agent.py", line 246, in step
    super().step()
  File "/private/home/kavyasrinet/droidlet/agents/core.py", line 29, in step
    self.controller_step()
  File "/private/home/kavyasrinet/droidlet/agents/loco_mc_agent.py", line 346, in controller_step
    self.memory.dialogue_stack.step(self)
  File "/private/home/kavyasrinet/droidlet/droidlet/memory/dialogue_stack.py", line 46, in step
    output_chat, step_data = self.stack[-1].step(agent=agent)
  File "/private/home/kavyasrinet/droidlet/droidlet/interpreter/interpreter.py", line 102, in step
    r = self.action_handlers[action_type](agent, self.speaker, action_def)
TypeError: handle_get() takes 3 positional arguments but 4 were given
2021-07-15 21:25:55,680 [loco_mc_agent.py:223 - handle_exception() ERROR]: Default handler caught exception, db_log_idx=221211
Traceback (most recent call last):
  File "/private/home/kavyasrinet/droidlet/agents/core.py", line 21, in start
    self.step()
  File "/private/home/kavyasrinet/droidlet/agents/loco_mc_agent.py", line 246, in step
    super().step()
  File "/private/home/kavyasrinet/droidlet/agents/core.py", line 29, in step
    self.controller_step()
  File "/private/home/kavyasrinet/droidlet/agents/loco_mc_agent.py", line 346, in controller_step
    self.memory.dialogue_stack.step(self)
  File "/private/home/kavyasrinet/droidlet/droidlet/memory/dialogue_stack.py", line 46, in step
    output_chat, step_data = self.stack[-1].step(agent=agent)
  File "/private/home/kavyasrinet/droidlet/droidlet/interpreter/interpreter.py", line 102, in step
    r = self.action_handlers[action_type](agent, self.speaker, action_def)
TypeError: handle_get() takes 3 positional arguments but 4 were given
Traceback (most recent call last):
  File "craftassist/craftassist_agent.py", line 473, in <module>
    sa.start()
  File "/private/home/kavyasrinet/droidlet/agents/core.py", line 23, in start
    self.handle_exception(e)
  File "/private/home/kavyasrinet/droidlet/agents/loco_mc_agent.py", line 241, in handle_exception
    raise e
  File "/private/home/kavyasrinet/droidlet/agents/core.py", line 21, in start
    self.step()
  File "/private/home/kavyasrinet/droidlet/agents/loco_mc_agent.py", line 246, in step
    super().step()
  File "/private/home/kavyasrinet/droidlet/agents/core.py", line 29, in step
    self.controller_step()
  File "/private/home/kavyasrinet/droidlet/agents/loco_mc_agent.py", line 346, in controller_step
    self.memory.dialogue_stack.step(self)
  File "/private/home/kavyasrinet/droidlet/droidlet/memory/dialogue_stack.py", line 46, in step
    output_chat, step_data = self.stack[-1].step(agent=agent)
  File "/private/home/kavyasrinet/droidlet/droidlet/interpreter/interpreter.py", line 102, in step
    r = self.action_handlers[action_type](agent, self.speaker, action_def)
TypeError: handle_get() takes 3 positional arguments but 4 were given
(droidlet_env) kavyasrinet@devfair0173:~/droid
```

**Comment by kavyasrinet** [comment]
Fixed
